# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestNewsSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'
pod 'Alamofire'
pod 'AlamofireObjectMapper', '~> 5.2'
pod 'SDWebImage'
end
